# Generated by Django 3.0 on 2024-12-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('product_image', models.ImageField(upload_to='Products')),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
