# Generated by Django 3.0 on 2025-01-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0003_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nitrogen', models.CharField(max_length=70)),
                ('Phosphorous', models.CharField(max_length=70)),
                ('Potassium', models.CharField(max_length=70)),
                ('Temperature', models.CharField(max_length=70)),
                ('PH', models.CharField(max_length=70)),
                ('Humidity', models.CharField(max_length=70)),
                ('Rainfall', models.CharField(max_length=70)),
                ('Recommend_Crop', models.CharField(max_length=70)),
            ],
        ),
    ]
